# Smoke test for Phase 36 plan 01 task T7 — sync idempotency (timestamp-aware)
# Strip timestamp line before hashing — precedent from v1.9 Phase 29 SUMMARY.
$tmp = New-Item -ItemType Directory -Path (Join-Path $env:TEMP "kit-sync-phase36-$(Get-Random)")
Write-Output "tmpdir: $($tmp.FullName)"

function Get-NormalizedHash {
    param($filePath)
    $content = (Get-Content $filePath -Raw) -replace '> Generated by kit-mcp at [0-9TZ:.\-]+\.', '> Generated by kit-mcp at <STRIPPED>.'
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($content)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $hash = $sha.ComputeHash($bytes)
    return [System.BitConverter]::ToString($hash) -replace '-', ''
}

# First sync run
& node "D:/projetos/opensource/mcp/bin/cli.js" sync install claude-code --project-root $tmp.FullName 2>&1 | Out-Null

# First snapshot — normalized sha256 of all files in skills (timestamp stripped)
$skillsPath = Join-Path $tmp.FullName ".claude\skills"
$first = Get-ChildItem -Recurse $skillsPath -File | Sort-Object FullName | ForEach-Object {
    $h = Get-NormalizedHash $_.FullName
    "$($_.FullName.Substring($skillsPath.Length))=$h"
}

# Second sync run
& node "D:/projetos/opensource/mcp/bin/cli.js" sync install claude-code --project-root $tmp.FullName 2>&1 | Out-Null

# Second snapshot
$second = Get-ChildItem -Recurse $skillsPath -File | Sort-Object FullName | ForEach-Object {
    $h = Get-NormalizedHash $_.FullName
    "$($_.FullName.Substring($skillsPath.Length))=$h"
}

# Compare
$diff = Compare-Object -ReferenceObject $first -DifferenceObject $second
if ($null -eq $diff) {
    Write-Output "IDEMPOTENT_OK"
} else {
    Write-Output "IDEMPOTENT_FAIL"
    $diff | ForEach-Object { Write-Output $_ }
}

# Sanity — _shared-sre/glossary should NOT be materialized in .claude/skills/
$glossaryPath = Join-Path $tmp.FullName ".claude\skills\_shared-sre\glossary.md"
if (Test-Path $glossaryPath) {
    Write-Output "SHOULD_NOT_BE_MATERIALIZED"
} else {
    Write-Output "NOT_MATERIALIZED_OK"
}

# Sanity — listKit should NOT include _shared-sre
$listOutput = & node "D:/projetos/opensource/mcp/bin/cli.js" kit list-skills 2>&1 | Out-String
if ($listOutput -match "_shared-sre") {
    Write-Output "SHOULD_NOT_BE_LISTED"
} else {
    Write-Output "NOT_LISTED_OK"
}

# Sanity — kit/skills/_shared-sre/glossary.md exists in kit source
$kitGlossary = "D:/projetos/opensource/mcp/kit/skills/_shared-sre/glossary.md"
if (Test-Path $kitGlossary) {
    $size = (Get-Item $kitGlossary).Length
    Write-Output "KIT_GLOSSARY_OK size=$size bytes"
} else {
    Write-Output "KIT_GLOSSARY_MISSING"
}

# Cleanup
Remove-Item -Recurse -Force $tmp.FullName
