// PERF-16-01: regression tests for syncTo() Promise.all batching.
// Validates correctness under batched writes, race-condition safety with
// concurrent syncTo invocations, and KIT_MCP_SYNC_BATCH_SIZE env validation.
//
// Wall-time speedup is verified manually (≥30% target captured in SUMMARY.md);
// flakey timing assertions are intentionally avoided here.

import { test, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import fs from 'node:fs/promises';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { syncTo } from '../../src/core/sync.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SAMPLE_KIT = path.resolve(__dirname, '../fixtures/sample-kit');

let TMP;

beforeEach(async () => {
  TMP = await fs.mkdtemp(path.join(os.tmpdir(), 'kit-mcp-conc-'));
});

afterEach(async () => {
  await fs.rm(TMP, { recursive: true, force: true });
});

// Save/restore env helper — Node.js test runner has no built-in env scoping.
async function runWithEnv(value, fn) {
  const KEY = 'KIT_MCP_SYNC_BATCH_SIZE';
  const prev = process.env[KEY];
  if (value === undefined) delete process.env[KEY];
  else process.env[KEY] = value;
  try { return await fn(); }
  finally {
    if (prev === undefined) delete process.env[KEY];
    else process.env[KEY] = prev;
  }
}

test('syncTo — batched writes deliver all expected files (correctness)', async () => {
  const calls = [];
  const onProgress = (e) => calls.push(e);

  const result = await syncTo('claude-code', {
    kitRoot: SAMPLE_KIT,
    projectRoot: TMP,
    onProgress,
  });

  // All files in sample-kit fixture should be present (rules + agent + 2 commands +
  // skill + workflow + 2 mirror-tree files + 2 .kit-mcp-managed markers).
  const expected = [
    'CLAUDE.md',
    '.claude/agents/sample-agent.md',
    '.claude/commands/sample-command.md',
    '.claude/commands/no-frontmatter-command.md',
    '.claude/skills/sample-skill/SKILL.md',
    '.claude/workflows/sample-dynamic-workflow.workflow.js',
    '.claude/framework/.kit-mcp-managed',
    '.claude/framework/workflows/sample-workflow.md',
    '.claude/hooks/.kit-mcp-managed',
    '.claude/hooks/sample-hook.js',
  ];
  for (const rel of expected) {
    await fs.access(path.join(TMP, rel)); // throws if missing
  }
  assert.equal(result.written.length, expected.length, 'written count must match expected files');

  // onProgress monotonic 1→N — counter shared across batched ops, so values
  // must increase by exactly 1 each call even though ops resolve out-of-order.
  assert.equal(calls.length, expected.length, 'onProgress called once per op');
  const total = calls[0].total;
  for (let i = 0; i < calls.length; i += 1) {
    assert.equal(calls[i].current, i + 1, `progress.current monotonic at index ${i}`);
    assert.equal(calls[i].total, total, 'progress.total stable across calls');
    assert.ok(calls[i].label, 'progress.label present');
  }
});

test('syncTo — 2× concurrent invocations do not produce torn writes', async () => {
  const target1 = path.join(TMP, 'p1');
  const target2 = path.join(TMP, 'p2');
  await fs.mkdir(target1);
  await fs.mkdir(target2);

  // Spawn two concurrent syncTo calls — both walk the SAME kitRoot but write
  // to DIFFERENT projectRoots. Exercises the batch loop in parallel; if there
  // were any shared mutable state in syncTo (there isn't), torn writes would
  // surface as content divergence between the two targets.
  await Promise.all([
    syncTo('claude-code', { kitRoot: SAMPLE_KIT, projectRoot: target1 }),
    syncTo('claude-code', { kitRoot: SAMPLE_KIT, projectRoot: target2 }),
  ]);

  // Byte-equal comparison of a known-stable file in both targets.
  const a1 = await fs.readFile(path.join(target1, '.claude/agents/sample-agent.md'));
  const a2 = await fs.readFile(path.join(target2, '.claude/agents/sample-agent.md'));
  // Stub renderers embed `new Date().toISOString()` so the timestamps may
  // differ by a millisecond. Strip the generation-time line before comparing.
  const stripTs = (buf) => buf.toString('utf8').replace(/Generated by kit-mcp at .+\n/, '');
  assert.equal(stripTs(a1), stripTs(a2), 'concurrent syncTo produces identical stub content (no tearing)');

  // STUB_MARKER must be present in both — rules out a partial write.
  const r1 = await fs.readFile(path.join(target1, '.claude/agents/sample-agent.md'), 'utf8');
  const r2 = await fs.readFile(path.join(target2, '.claude/agents/sample-agent.md'), 'utf8');
  assert.match(r1, /<!-- kit-mcp:reference -->/);
  assert.match(r2, /<!-- kit-mcp:reference -->/);
});

test('KIT_MCP_SYNC_BATCH_SIZE — valid value (4) is honored, sync still completes', async () => {
  await runWithEnv('4', async () => {
    const result = await syncTo('claude-code', { kitRoot: SAMPLE_KIT, projectRoot: TMP });
    assert.ok(result.written.length > 0);
    await fs.access(path.join(TMP, '.claude/agents/sample-agent.md'));
  });
});

test('KIT_MCP_SYNC_BATCH_SIZE — non-numeric falls back to default 16, sync completes', async () => {
  await runWithEnv('not-a-number', async () => {
    const result = await syncTo('claude-code', { kitRoot: SAMPLE_KIT, projectRoot: TMP });
    assert.ok(result.written.length > 0);
    await fs.access(path.join(TMP, '.claude/agents/sample-agent.md'));
  });
});

test('KIT_MCP_SYNC_BATCH_SIZE — out-of-range (999) falls back to default 16, sync completes', async () => {
  await runWithEnv('999', async () => {
    const result = await syncTo('claude-code', { kitRoot: SAMPLE_KIT, projectRoot: TMP });
    assert.ok(result.written.length > 0);
    await fs.access(path.join(TMP, '.claude/agents/sample-agent.md'));
  });
});

test('KIT_MCP_SYNC_BATCH_SIZE — zero falls back to default 16, sync completes', async () => {
  await runWithEnv('0', async () => {
    const result = await syncTo('claude-code', { kitRoot: SAMPLE_KIT, projectRoot: TMP });
    assert.ok(result.written.length > 0);
    await fs.access(path.join(TMP, '.claude/agents/sample-agent.md'));
  });
});
