// Workflows capability — added in v1.34.0.
// Covers: kit loader (meta parsing), sync projection (JS header + content),
// reverse-sync (stub detection + boilerplate stripping), registry exposure.

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

import { listKit, findItem, searchKit, clearKitCache } from '../../src/core/kit.js';
import { syncTo, statusOf, removeFrom } from '../../src/core/sync.js';
import { detectReverse } from '../../src/core/reverse-sync.js';
import { listTargets, TARGETS } from '../../src/core/registry.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE   = path.resolve(__dirname, '../fixtures/sample-kit');

process.env.KIT_MCP_SKIP_MANIFEST_CHECK = '1';

let TMP;
test.beforeEach(async () => {
  TMP = await fs.mkdtemp(path.join(os.tmpdir(), 'kit-mcp-workflows-'));
  clearKitCache();
});
test.afterEach(async () => { await fs.rm(TMP, { recursive: true, force: true }); });

test('registry — claude-code declares workflows capability with .workflow.js extension', () => {
  assert.equal(TARGETS['claude-code'].workflows.path, '.claude/workflows/');
  assert.equal(TARGETS['claude-code'].workflows.extension, '.workflow.js');
  assert.equal(TARGETS['claude-code'].workflows.minPlan, 'max');
});

test('registry — non-claude-code targets declare workflows: null', () => {
  for (const id of ['cursor', 'codex', 'gemini-cli', 'copilot', 'windsurf', 'antigravity', 'trae']) {
    assert.equal(TARGETS[id].workflows, null, `${id} should not advertise workflows`);
  }
});

test('listTargets — includes workflows capability bit', () => {
  const targets = listTargets();
  const cc = targets.find(t => t.id === 'claude-code');
  assert.equal(cc.capabilities.workflows, true);
  const cur = targets.find(t => t.id === 'cursor');
  assert.equal(cur.capabilities.workflows, false);
});

test('listKit — picks up kit/workflows/*.workflow.js with name + description from meta literal', async () => {
  const kit = await listKit(FIXTURE);
  assert.equal(kit.workflows.length, 1, 'fixture has 1 workflow');
  const wf = kit.workflows[0];
  assert.equal(wf.kind, 'workflow');
  assert.equal(wf.name, 'sample-dynamic-workflow');
  assert.equal(wf.fileBase, 'sample-dynamic-workflow');
  assert.match(wf.description, /Fixture workflow/);
});

test('searchKit + findItem — kind:"workflow" works', async () => {
  const kit = await listKit(FIXTURE);
  const found = searchKit(kit, 'sample-dynamic');
  assert.ok(found.some(x => x.kind === 'workflow'));
  const item = findItem(kit, 'workflow', 'sample-dynamic-workflow');
  assert.ok(item);
  assert.equal(item.name, 'sample-dynamic-workflow');
});

test('syncTo — projects workflow to .claude/workflows/ with JS provenance header', async () => {
  await syncTo('claude-code', { kitRoot: FIXTURE, projectRoot: TMP });
  const outPath = path.join(TMP, '.claude/workflows/sample-dynamic-workflow.workflow.js');
  const content = await fs.readFile(outPath, 'utf8');
  assert.match(content, /^\/\/ kit-mcp:reference/);
  assert.match(content, /Canonical source:/);
  assert.match(content, /Edit the source file in the kit/);
  assert.match(content, /Generated by kit-mcp at \d{4}-\d{2}-\d{2}T/);
  // The original meta block must still be present and parseable as JS.
  assert.match(content, /export const meta = \{/);
  assert.match(content, /name: 'sample-dynamic-workflow'/);
});

test('syncTo — non-supported target (cursor) does NOT write workflows dir', async () => {
  await syncTo('cursor', { kitRoot: FIXTURE, projectRoot: TMP });
  await assert.rejects(
    fs.access(path.join(TMP, '.cursor/workflows/')),
    'cursor must not get a workflows directory'
  );
});

test('statusOf — reports workflows capability check', async () => {
  await syncTo('claude-code', { kitRoot: FIXTURE, projectRoot: TMP });
  const status = await statusOf('claude-code', { projectRoot: TMP });
  const wf = status.checks.find(c => c.capability === 'workflows');
  assert.ok(wf, 'workflows capability must appear in status');
  assert.equal(wf.exists, true);
});

test('removeFrom — deletes workflow stubs (preserves user-authored)', async () => {
  await syncTo('claude-code', { kitRoot: FIXTURE, projectRoot: TMP });
  const userPath = path.join(TMP, '.claude/workflows/my-own.workflow.js');
  await fs.writeFile(userPath, 'export const meta = { name: "my-own", description: "mine" }\nphase("X")\n');
  await removeFrom('claude-code', { projectRoot: TMP });
  await assert.rejects(fs.access(path.join(TMP, '.claude/workflows/sample-dynamic-workflow.workflow.js')));
  const userContent = await fs.readFile(userPath, 'utf8');
  assert.match(userContent, /my-own/);
});

test('CLAUDE.md aggregated rules — includes Workflows section when target supports + kit ships any', async () => {
  await syncTo('claude-code', { kitRoot: FIXTURE, projectRoot: TMP });
  const claudeMd = await fs.readFile(path.join(TMP, 'CLAUDE.md'), 'utf8');
  assert.match(claudeMd, /## Workflows \(Dynamic Workflows/);
  assert.match(claudeMd, /\*\*sample-dynamic-workflow\*\*/);
});

test('detectReverse — unmodified workflow stub is not flagged', async () => {
  await syncTo('claude-code', { kitRoot: FIXTURE, projectRoot: TMP });
  const result = await detectReverse('claude-code', { kitRoot: FIXTURE, projectRoot: TMP });
  const wfCandidates = result.candidates.filter(c => c.kind === 'workflow');
  assert.equal(wfCandidates.length, 0, 'clean stub must not appear in reverse-sync candidates');
});

test('detectReverse — modified workflow is flagged modified-in-ide', async () => {
  await syncTo('claude-code', { kitRoot: FIXTURE, projectRoot: TMP });
  const outPath = path.join(TMP, '.claude/workflows/sample-dynamic-workflow.workflow.js');
  const original = await fs.readFile(outPath, 'utf8');
  await fs.writeFile(outPath, original + '\n// user edit\nlog("modified locally")\n');
  const result = await detectReverse('claude-code', { kitRoot: FIXTURE, projectRoot: TMP });
  const flagged = result.candidates.find(c => c.kind === 'workflow' && c.name === 'sample-dynamic-workflow');
  assert.ok(flagged, 'edited workflow must surface');
  assert.equal(flagged.reason, 'modified-in-ide');
});

test('detectReverse — workflow not in kit is flagged new-in-ide', async () => {
  await syncTo('claude-code', { kitRoot: FIXTURE, projectRoot: TMP });
  const userPath = path.join(TMP, '.claude/workflows/orphan.workflow.js');
  await fs.writeFile(userPath, 'export const meta = { name: "orphan", description: "user-authored" }\nphase("X")\n');
  const result = await detectReverse('claude-code', { kitRoot: FIXTURE, projectRoot: TMP });
  const flagged = result.candidates.find(c => c.name === 'orphan');
  assert.ok(flagged);
  assert.equal(flagged.reason, 'new-in-ide');
});

test('meta parser — handles description with `+` chars inside literal (false-positive bait)', async () => {
  const kit = await listKit(path.resolve(__dirname, '../../kit'));
  const real = kit.workflows.find(w => w.name === 'auditar-observabilidade-cobertura');
  assert.ok(real, 'real workflow loaded');
  assert.match(real.description, /v1\.9 Observability \+ v1\.10 SRE \+ v1\.12 Legacy/);
});
